### ISSUE TITLE
error with rails

### ISSUE THREAD

**Issue by xero88** [mech/filemaker-ruby#11]
/var/lib/gems/2.4.0/gems/filemaker-0.0.19/lib/filemaker.rb:38:in `block (2 levels) in load!': undefined method `fetch' for "host.com":String (NoMethodError)

My filemaker.yml : 

```
development:
  host: host.com
  account_name: test
  password: test
  ssl: true
  log: curl
```

**Comment by mech** [comment]
Hi, tks for using the gem, you need to specify the default because I was thinking of slave FM server that time. But I should probably remove it:

```
development:
  default:
    host: <%= ENV['FILEMAKER_HOST'] %>
    account_name: <%= ENV['FILEMAKER_ACCOUNT_NAME'] %>
    password: <%= ENV['FILEMAKER_PASSWORD'] %>
    ssl: { verify: false }
    log: simple
```
